import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

const green1 = Color(0xFF5CAF56);
const green2 = Color(0xFF092313);
const green3 = Color(0xFFAED038);
const green4 = Color(0xFF5DB075);
const greenGray= Color(0xFFA7BEAE);
const mediumGray= Color(0xFFDCE0D5);
const lightGray= Color(0xFFF3F3F3);
const red= Color(0xFFEB4335);
const blue= Color(0xFFA3F9F0);
BorderRadius borderRadius=BorderRadius.circular(10);
BorderSide borderSideGreen=const BorderSide(color: green4,width:2.0);
BorderSide borderSideWhite=const BorderSide(color: Colors.white);
TextStyle heading1=GoogleFonts.almarai(fontSize: 55,color:green2,fontWeight:FontWeight.w700);
TextStyle heading2=GoogleFonts.outfit(fontSize: 36,color: Colors.black,fontWeight:FontWeight.w700);
TextStyle heading2Green=GoogleFonts.outfit(fontSize: 20,color:green1,fontWeight:FontWeight.w700);
TextStyle success= GoogleFonts.almarai(fontSize:18,color: green1,fontWeight:FontWeight.w700);
TextStyle label=GoogleFonts.almarai(fontSize: 15,fontWeight:FontWeight.w700);
TextStyle price=GoogleFonts.almarai(fontSize: 14,color:green1,fontWeight:FontWeight.w700);
TextStyle titleProduct=GoogleFonts.almarai(fontSize:13,fontWeight:FontWeight.w700);
TextStyle title=GoogleFonts.almarai(fontSize:15,color:green1,fontWeight:FontWeight.w500);
TextStyle snackBarFonts=GoogleFonts.almarai(fontSize:15,fontWeight:FontWeight.w400,color:Colors.white);
