import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

const green1 = Color(0xFF5CAF56);
const green2 = Color(0xFF092313);
const green3 = Color(0xFFAED038);
const green4 = Color(0xFF5DB075);
const greenGray= Color(0xFFA7BEAE);
const mediumGray= Color(0xFFDCE0D5);
const lightGray= Color(0xFFF3F3F3);
const red= Color(0xFFEB4335);
const blue= Color(0xFFA3F9F0);
BorderRadius borderRadius=BorderRadius.circular(10);
BorderSide borderSideGreen=const BorderSide(color: green4,width:2.0);
BorderSide borderSideWhite=const BorderSide(color: Colors.white);
TextStyle heading1=GoogleFonts.outfit(fontSize: 55,color:green2,fontWeight:FontWeight.w700);
TextStyle heading2=GoogleFonts.outfit(fontSize: 40,color: Colors.black,fontWeight:FontWeight.w700);
TextStyle heading2Green=GoogleFonts.outfit(fontSize: 40,color:green1,fontWeight:FontWeight.w700);
TextStyle heading3=GoogleFonts.outfit(fontSize: 35,color: Colors.black,fontWeight:FontWeight.w700);
TextStyle title1=GoogleFonts.almarai(fontSize:28,color:green1,fontWeight:FontWeight.w700);
TextStyle title2=GoogleFonts.almarai(fontSize:22,color:green1,fontWeight:FontWeight.w700);
TextStyle title2Black=GoogleFonts.almarai(fontSize:22,color:Colors.black,fontWeight:FontWeight.w700);
TextStyle titleProduct=GoogleFonts.almarai(fontSize:20,fontWeight:FontWeight.w500);
TextStyle title3=GoogleFonts.almarai(fontSize:18,color:green1,fontWeight:FontWeight.w700);
TextStyle title3Black=GoogleFonts.almarai(fontSize:18,color:Colors.black,fontWeight:FontWeight.w700);
TextStyle body1Green=GoogleFonts.almarai(fontSize:14,color:green1,fontWeight:FontWeight.w500);
TextStyle body1Black=GoogleFonts.almarai(fontSize:14,color:Colors.black,fontWeight:FontWeight.w500);
TextStyle label=GoogleFonts.outfit(fontSize: 15,fontWeight:FontWeight.w500);
TextStyle price1=GoogleFonts.almarai(fontSize: 25,color:green1,fontWeight:FontWeight.w700);
TextStyle snackBarFonts=GoogleFonts.almarai(fontSize:15,fontWeight:FontWeight.w400,color:Colors.white);
TextStyle subTitleFonts=GoogleFonts.almarai(fontSize:13,fontWeight:FontWeight.w400,color:Colors.grey);
