// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSORNtRlzNmKLLErEOzAoQrsraiPPEBo',
    appId: '1:709354686529:web:56195886e62c3029e71ec0',
    messagingSenderId: '709354686529',
    projectId: 'green-circle-cfdd9',
    authDomain: 'green-circle-cfdd9.firebaseapp.com',
    storageBucket: 'green-circle-cfdd9.appspot.com',
    measurementId: 'G-KLDCKNR4QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa710JhAgetfiI9Hfb6A3mlsJ5mcSB5lY',
    appId: '1:709354686529:android:7e38cdf43bb38ed8e71ec0',
    messagingSenderId: '709354686529',
    projectId: 'green-circle-cfdd9',
    storageBucket: 'green-circle-cfdd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpgFFGOA14UCq9qfa-Aj8-oRgPliGwdnk',
    appId: '1:709354686529:ios:1f9ebd6e440e3b8be71ec0',
    messagingSenderId: '709354686529',
    projectId: 'green-circle-cfdd9',
    storageBucket: 'green-circle-cfdd9.appspot.com',
    iosBundleId: 'com.example.greenCircle',
  );
}
